# BEGIN
spring:
  datasource:
    url: jdbc:h2:file:./test
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true  # Включает веб-консоль H2 для отладки
# END
